- name: Dependecnies ios_command reporting
  hosts: routers
  gather_facts: false

  tasks:
    - name: Run a show command
      cisco.ios.ios_command:
        commands:
          - show clock
      register: output
